CREATE TABLE appointment(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    doctor_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    `date` DATETIME NOT NULL,
    CONSTRAINT FK_APPOINTMENT_APPOINTMENT FOREIGN KEY (doctor_id) REFERENCES doctor(id),
    CONSTRAINT FK_APPOINTMENT_PATIENT FOREIGN KEY (patient_id) REFERENCES patient(id)
);